Adding JSNLog module [DDFLSBP-569]
danskernesdigitalebibliotek/dpl-cms pull request #1077
Opened 2024-05-01 09:29 UTC by clausbruun

#### Link to issue

https://reload.atlassian.net/browse/DDFLSBP-569

#### Description

Adding JSNLog module.

#### Screenshot of the result

![image](https://github.com/danskernesdigitalebibliotek/dpl-cms/assets/105956/10a3e85f-51f9-4cdd-b3c4-034bdbc72bf0)

2024-05-06 12:52 UTC, Adamik10 approved these changes
Very good! Love the ADR inclusion :))

2024-06-24 12:00 UTC, Dresse requested changes
LGTM 👍 

However after introducing config_ignore_auto, the core.extension.yml has been added to config_ignore. This means that new modules should be installed in an update hook in dpl_update module.

You can see it here:
https://github.com/danskernesdigitalebibliotek/dpl-cms/blob/develop/web/modules/custom/dpl_update/dpl_update.install

2024-06-26 11:46 UTC, clausbruun commented
> LGTM 👍
> 
> However after introducing config_ignore_auto, the core.extension.yml has been added to config_ignore. This means that new modules should be installed in an update hook in dpl_update module.
> 
> You can see it here: https://github.com/danskernesdigitalebibliotek/dpl-cms/blob/develop/web/modules/custom/dpl_update/dpl_update.install

@Dresse: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1077/commits/1ec893443d56749feefc6a8095d67d9469fec909 :)

2024-06-26 12:14 UTC, spaceo commented on composer.json
> +                    "url": "https://github.com/danskernesdigitalebibliotek/dpl-react/releases/download/branch-feature%2FDDFLSBP-569-logging-i-frontend/dist-feature-ddflsbp-569-logging-i-frontend.zip"
Remember to remove this change

2024-06-26 12:14 UTC, spaceo commented on composer.json
> +                    "url": "https://github.com/danskernesdigitalebibliotek/dpl-design-system/releases/download/branch-develop/dist-develop.zip",
Remember to remove this change

2024-06-26 12:15 UTC, spaceo commented on composer.json
> +        "danskernesdigitalebibliotek/dpl-react": "2024.22.2-dev",
Remember to remove these change

2024-06-26 14:03 UTC, Dresse commented
> > LGTM 👍
> > However after introducing config_ignore_auto, the core.extension.yml has been added to config_ignore. This means that new modules should be installed in an update hook in dpl_update module.
> > You can see it here: https://github.com/danskernesdigitalebibliotek/dpl-cms/blob/develop/web/modules/custom/dpl_update/dpl_update.install
> 
> @Dresse: [1ec8934](https://github.com/danskernesdigitalebibliotek/dpl-cms/commit/1ec893443d56749feefc6a8095d67d9469fec909) :)

Nice Claus!
I can see that the previous process has been to both enable modules in core.extensions.yml and in dpl_update. I was not clear about that earlier, I'm sorry!

Also I can see that it should also be added as part of the dpl_update_install hook in dpl_update.install

2024-06-26 14:10 UTC, clausbruun commented
> Nice Claus! I can see that the previous process has been to both enable modules in core.extensions.yml and in dpl_update. I was not clear about that earlier, I'm sorry!
> 
> Also I can see that it should also be added as part of the dpl_update_install hook in dpl_update.install

@Dresse: Just to clarify, in your opinion, are there any further changes that I should make? :)

2024-06-26 14:17 UTC, Dresse commented
> > Nice Claus! I can see that the previous process has been to both enable modules in core.extensions.yml and in dpl_update. I was not clear about that earlier, I'm sorry!
> > Also I can see that it should also be added as part of the dpl_update_install hook in dpl_update.install
> 
> @Dresse: Just to clarify, in your opinion, are there any further changes that I should make? :)

Yes, I think one more change is needed. 
We need to add this `$messages[] = dpl_update_update_10008();` to the dpl_update_install hook in dpl_update.install file 👍

2024-06-26 14:24 UTC, Dresse approved these changes
LGTM 👍

2024-06-26 14:24 UTC, clausbruun commented
> Yes, I think one more change is needed. We need to add this `$messages[] = dpl_update_update_10008();` to the dpl_update_install hook in dpl_update.install file 👍

Done: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1077/commits/b33791c3cb312cad9607ae20095af912b59c92a0

2024-06-27 11:08 UTC, merged