indloggetudlogget funktionalitet DDFSOEG 178
danskernesdigitalebibliotek/dpl-cms pull request #122
Opened 2022-08-26 07:03 UTC by spaceo

- Add missing text props to search header
- Update data attribute name for setting search result url in header
- Add properties as data attributes for search result
- Change wording and routing around materials to works
- Add all known props to the work/material app
- Build urls for works/materials from route definition
- Add method to controller for managing search result urls
- DO NOT MERGE: Use demo builds of dependencies

#### Link to issue

Please add a link to the issue being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2022-08-30 12:51 UTC, kasperg requested changes
A couple of things need changing here and a few things for you to consider.

I have only reviewed parts of the PR not already included in #120 .

Also remember to remove commits with custom builds before merging.

2022-08-30 12:51 UTC, kasperg commented on web/modules/custom/dpl_login/src/Controller/DplLoginController.php
> +    return new TrustedRedirectResponse($client->getAuthorizationEndpointUrl("openid email profile"));
Consider if adding `getAuthorizationEndpointUrl()` is the right approach for maintainability going forward.

I have looked into [the patch](https://www.drupal.org/files/issues/2022-08-26/openid_connect-auth-endpoint.patch) and this code that uses the patch.

As far as I can tell it seems as if the patch creates a method in the `OpenIDConnectClientBase` for generating an url which this method then passes to a `TrustedRedirectResponse`. Without the patch [the `authorize` method the the class seems to return the same url wrapped in a `TrustedRedirectResponse`](https://git.drupalcode.org/project/openid_connect/-/blob/8.x-1.x/src/Plugin/OpenIDConnectClientBase.php#L256). Why not just call `$client->authorize()` and return the result.

[This approach is used to solve a similar problem in Gruppeweb](https://github.com/reload/gruppeweb/blob/main/web/modules/custom/gruppeweb_login/src/Controller/Login.php#L99-L123).

2022-08-31 07:05 UTC, spaceo commented on composer.json
> +                "Expose authorization url endpoint": "https://www.drupal.org/files/issues/2022-08-26/openid_connect-auth-endpoint.patch"
removing the patch...

2022-08-31 07:06 UTC, spaceo commented on web/modules/custom/dpl_login/dpl_login.routing.yml
> +    _title: 'Authorize From App'
done

2022-08-31 07:19 UTC, cableman approved these changes

2022-08-31 09:56 UTC, merged