Change event time settings to allow events to start from 00:00
danskernesdigitalebibliotek/dpl-cms pull request #1337
Opened 2024-07-04 10:53 UTC by kasperbirch1

#### Link to issue
https://reload.atlassian.net/browse/DDFFORM-877

#### Description

Because we use AM/PM time, I have changed the `min_time` to 12:00 AM, which is the same as 00:00 in our timezone.

#### Test

2024-07-08 06:22 UTC, kasperg requested changes
Please reconsider your approach to this task:

The original request was:

1. It must be possible to choose any number of minutes on all types of events - right now it is only possible on individual events.
2. It must be possible to start an event before 8 am.
3. It must be possible for an event to run from 00:00-00:00. In that case, the text "all day" must be displayed at the event.

Part 3 has been moved to a separate task. As I see it the current change only solves part 2, but what about part 1?

2024-07-09 05:43 UTC, kasperg approved these changes

2024-07-12 13:16 UTC, kasperbirch1 commented
Venter på https://reload.atlassian.net/browse/DDFFORM-947

2024-08-12 11:32 UTC, kasperbirch1 commented
@rasben I have assigned you as you have overtaken the ticket. ☺️

2024-08-15 10:55 UTC, closed without merging