WIP: Ddfform 810 links open in new window tab
danskernesdigitalebibliotek/dpl-cms pull request #1346
Opened 2024-07-08 09:44 UTC by kasperbirch1

#### Link to issue

Please add a link to the issue being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2024-07-16 07:13 UTC, rasben requested changes

2024-07-16 07:13 UTC, rasben commented on config/sync/core.extension.yml
> +  linkit_attributes: 0
New modules must be enabled using a deploy hook

2024-07-16 09:10 UTC, rasben approved these changes

2024-08-02 14:08 UTC, kasperbirch1 commented
This has been replaced by: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1449

2024-08-02 14:08 UTC, closed without merging