Branch blacklist admin
danskernesdigitalebibliotek/dpl-cms pull request #153
Opened 2022-10-26 12:46 UTC by kasperg

#### Link to issue

Please add a link to the issue being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My complies with [our coding guidelines](../documentation/code-guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2022-10-27 07:22 UTC, kasperg commented on composer.json
> +                    "url": "https://github.com/reload/dpl-react/releases/download/release-blacklist-search-result/dist.zip",
This should be reverted before this PR is merged.

2022-10-31 12:10 UTC, spaceo reviewed
Please remember to document the packages directory

2022-10-31 12:28 UTC, spaceo approved these changes
LGTM 👍

2022-10-31 12:29 UTC, spaceo commented on web/modules/custom/dpl_library_agency/src/FbsApiFactory.php
> +      ->setHost('https://fbs-openplatform.dbc.dk');
We agreed upon a TODO describing that it could be configurable in the future.

2022-10-31 13:15 UTC, kasperg commented on web/modules/custom/dpl_library_agency/src/Form/GeneralSettingsForm.php
> +  protected function t($string, array $args = [], array $options = []): TranslatableMarkup {
We cannot do that because the type is not specified in the parent function.

2022-11-01 13:30 UTC, turegjorup requested changes
We should either
1. Generate a full blown FBS client and publish it to it's own repository and package
2. Keep the client here but limit the generation to ONLY the functionality needed

One way to do that is to expand the ignore file as shown. But I am unsure if I have excluded to much.

2022-11-01 13:30 UTC, turegjorup commented on packages/fbs/composer.json
> +    "name": "danskernesdigitalebibliotek/fbs",
A better name would be `danskernesdigitalebibliotek/fbs-php-client`

2022-11-01 13:30 UTC, turegjorup commented on packages/fbs/.openapi-generator-ignore
> +
Consider adding

```
docs/**/*.*
lib/**/*.*

!*/Api/ExternalV1AgencyidApi.*
!*/Model/AgencyBranch.*
```

to exclude files not needed

2022-11-01 14:11 UTC, kasperg commented
> We should either [...] Generate a full blown FBS client and publish it to it's own repository and package

I do not think publishing the FBS client to its own repository and package is a good idea at the moment.

1. I do not think it has the maturity to merit its' own package. It is based on an unofficial specification of the FBS proxy.
2. We do not have other users of the package that I am aware of.
3. The package it itself has little value. It is more or less the result of running a tool and committing the result. Others might as well do the same. The real value is the specification.
4. Publishing the results has its' own problems. We need Guzzle 6 for Drupal 9. Usage with other frameworks might require Guzzle 7. Instead of maintaining multiple versions in parallel centrally we might as well let each use case generate with their own appropriate configuration.

We have not published our generated TypeScript clients for FBS, Material List etc. either.

> We should either [...] Keep the client here but limit the generation to ONLY the functionality needed

I would not mind us doing using the approach you suggested so but it would be good to get a shared understanding of why we think this is needed.

We have not done so for our generated TypeScript REST clients at the moment.

2022-11-02 09:45 UTC, turegjorup commented
> I do not think publishing the FBS client to its own repository and package is a good idea at the moment.

Mostly agree, and not important relative to this PR. (Longer term I would prefer a published client dependent on a PSR-18 http client. I think this would still be easier to adopt in other projects than everybody duplicating auto generation. But that is out of scope of this PR).

> I would not mind us doing using the approach you suggested so but it would be good to get a shared understanding of why we think this is needed.

2 reasons. 

- Having excess code that we know will never be used is never a good idea IMHO. I don't believe there is anything such as "free" code maintenance wise.  Even if it is auto generated. So if we can scope this to the code actually needed then this is preferable. 
- In the NEXT architecture _most_ calls to external service should happen in the front end from the react clients. Taking care to actively exclude endpoint from the PHP clients clearly signals to developers where endpoints should be called from an architectural perspective. I would argue that something similar should be done in the TypeScript clients to either exclude this endpoint, or alter it so that the TypeScript clients knows to call Drupal for a list of branches. Because it's highly unlikely that a user facing part of NEXT should ever need to display excluded branches. Not doing so leaves it as a responsibility of the individual developers to know what not code to call and not to call.  Thsi is a little bit along the lines of thinking behind [PHPArkitect](https://github.com/phparkitect/arkitect) where you build rules to enforce architectural decisions.

2022-11-08 07:26 UTC, kasperg commented
@turegjorup I tried to address/reflect these decisions in [61d1184](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/153/commits/61d1184582d087794ca75726a93932a259552583).

2022-11-08 09:14 UTC, turegjorup approved these changes

2022-11-08 09:51 UTC, merged