Webmaster doc
danskernesdigitalebibliotek/dpl-cms pull request #1559
Opened 2024-09-11 19:48 UTC by xendk

Add documentation about configuration handling in webmaster modules.

2024-09-11 19:49 UTC, xendk commented
I don't know why I get those merge commits, I've just rebased on `origin/main`.

2024-09-12 07:26 UTC, kasperg commented
> I don't know why I get those merge commits, I've just rebased on origin/main

Try rebasing against `develop` :smile:.  These are merge requests from `develop` into `main`. The PR is against `develop`.

2024-09-12 09:19 UTC, kasperg requested changes
:+1: Nice. I think this is well written.

There are some parts that I think needs to be addressed primarily usage of DPL and the document structure.

Please also consider if some parts actually belong in an ADR about configuration handling for custom modules for webmaster sites. This allows us to mention alternatives considered, known challenges, future perspectives etc. while this documentation only dealing with the practicalities and known processes.

2024-09-12 09:19 UTC, kasperg commented on docs/webmaster-modules.md
> +modifications, export and copy the changed files.
Consider explaining whether the developer also needs to ensure that the updated configuration is imported as a part of the change through custom code or should they wait for the next deployment of DPL CMS.

2024-09-12 09:19 UTC, kasperg commented on docs/webmaster-modules.md
> +service.
I had hoped that the code needed for configuration handling would be so simple that we could include it in the documentation.

I see that is not the case so referencing the Brug Byen module makes sense. It does point at infrastructure which could be provided by a central solution going forward.

2024-09-13 08:49 UTC, xendk commented on docs/webmaster-modules.md
> +## Overview
I considered making it "Webmaster modules configuration management" but that's a horrible title for the left side menu. I also considered whether there should be a toplevel "Webmaster sites" which this document should be a subpage of, but I don't know if the generator supports that kind of thing.

I don't think there's much more to add under the heading of "Webmaster modules", the configuration handling is pretty much the only thing that sets them apart from regular modules, so I think the structure works if we "reindent" from "Overview" and down.

2024-09-13 08:50 UTC, xendk commented on docs/webmaster-modules.md
> +the reader...
Well this was before we talked it through. Now we can describe the worst case scenario.

2025-01-07 07:42 UTC, merged