Handtering af placeholders og flertal i tekstrenge ddfsoeg 279
danskernesdigitalebibliotek/dpl-cms pull request #168
Opened 2022-11-10 13:05 UTC by spaceo

#### Link to issue

https://reload.atlassian.net/browse/DDFSOEG-279

#### Description

This PR's main focus is to make the text handling in dpl-cms compatible with the new version in dpl-react (https://github.com/danskernesdigitalebibliotek/dpl-react/pull/212)

What is being done:
* dpl_react_render detects if an application property is an array and converts the value to json if so. This is needed for more complex text values like plural definitions.
* changed the strings that has been changed in order to use the new format in dpl-react
* Adding strings from the serach related apps dpl-react that has not been added before.

#### Checklist

- [ ] My complies with [our coding guidelines](../documentation/code-guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2022-11-10 14:35 UTC, kasperg requested changes
Please read into the PHPStan comments

I wonder why it has not reported on the duplicate array entries in all the changesets.

2022-11-10 14:35 UTC, kasperg commented on web/modules/custom/dpl_react_apps/src/Controller/DplReactAppsController.php
> +        'find-on-shelf-modal-screen-reader-modal-description-text' => $this->t('Reservation modal screen reader description', [], $c),
Please rework the duplicated prop here.

2022-11-11 12:39 UTC, spaceo commented on web/modules/custom/dpl_react_apps/src/Controller/DplReactAppsController.php
> +        'find-on-shelf-modal-screen-reader-modal-description-text' => $this->t('Reservation modal screen reader description', [], $c),
👍

2022-11-11 12:39 UTC, spaceo commented on composer.json
> +                    "url": "https://github.com/reload/dpl-react/releases/download/release-handtering-af-placeholders-og-flertal-i-tekstrenge-DDFSOEG-279/dist.zip",
👍

2022-11-11 12:57 UTC, spaceo commented on web/modules/custom/dpl_react_apps/src/Controller/DplReactAppsController.php
> +        'infomedia-modal-screen-reader-modal-description-text' => $this->t('Modal for infomedia', [], $c),
👍

2022-11-11 13:00 UTC, kasperg approved these changes

2022-11-15 08:34 UTC, cableman approved these changes

2022-11-15 08:44 UTC, merged