Pa11y add reservation page
danskernesdigitalebibliotek/dpl-cms pull request #194
Opened 2022-12-12 11:18 UTC by spaceo

#### Link to issue

https://reload.atlassian.net/browse/DDFSOEG-324

#### Description

Add reservation modal as another view to be tested by Pa11y

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2022-12-16 08:52 UTC, cableman requested changes

2022-12-16 08:52 UTC, cableman commented on pa11y/src/mappings/reservation/data/fbi/patron.json
> +		"emailAddress": "john.johnson@johnmail.com",
Maybe use `example.com` which is block for testing. `johnmail.com` is currently owned by at domain shark... just to be sure to be sure... that this never ends up sending mails in anyway.

2022-12-16 10:15 UTC, cableman approved these changes

2023-01-17 08:16 UTC, Adamik10 approved these changes

2023-01-17 08:17 UTC, merged