End to end test autosuggest
danskernesdigitalebibliotek/dpl-cms pull request #216
Opened 2023-01-16 14:06 UTC by Adamik10

#### Link to issue

Please add a link to the issue being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2023-01-23 11:02 UTC, spaceo requested changes

2023-01-23 12:17 UTC, spaceo commented on cypress/e2e/user-journey.cy.ts
> +        url: "/opac/graphql",
And I see now that you also make use of the mocked data in /wiremock - which is good. And then it makes even more sense to do the matching in the same way.

2023-01-24 12:37 UTC, Adamik10 commented on cypress/e2e/user-journey.cy.ts
> +      .get(".autosuggest__text")
Uuuu we actually don't have any data-cy on autosuggest. I'll make a separate PR for it :)

2023-02-01 18:44 UTC, spaceo approved these changes
Great work. 👍

2023-02-07 09:52 UTC, jeppekroghitk approved these changes

2023-02-07 11:53 UTC, merged