End to end test material page
danskernesdigitalebibliotek/dpl-cms pull request #218
Opened 2023-01-17 11:01 UTC by Adamik10

#### Link to issue
https://reload.atlassian.net/browse/DDFSOEG-309

#### Description
This PR adds material page to the user journey cypress end-to-end test. The test checks whether key data that a user would be focusing on during their user journey is rendered and whether clicking on the reservation button opens a modal.

#### Screenshot of the result
n/a

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions
-

2023-01-23 14:11 UTC, spaceo requested changes
We need to talk about the mappings. There is one comment about the actual test I would like you to look at :)

2023-01-23 14:11 UTC, spaceo commented on cypress/e2e/user-journey.cy.ts
> +      response: {
There is one thing I would like to talk with you about looking at these mappings. I find it unnecessary to create the same mappings as we are using in the Pa11y and Lighthouse tests.

2023-01-23 14:11 UTC, spaceo commented on cypress/e2e/user-journey.cy.ts
> +      .should("contain", "Harry Potter og Fønixordenen");
I think we should use getBySel here

2023-02-01 14:45 UTC, Adamik10 commented
Became a part of #216

2023-02-01 14:45 UTC, closed without merging