ITKDev: Settings pattern
danskernesdigitalebibliotek/dpl-cms pull request #330
Opened 2023-05-24 14:03 UTC by cableman

#### Link to issue

https://jira.itkdev.dk/browse/CMN-636

#### Description

Applying the settings pattern used in dpl_instance_loan as requested in https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/313#discussion_r1200271788

#### Screenshot of the result

N/A

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

N/A

2023-05-26 10:20 UTC, sinejespersen approved these changes

2023-05-30 11:15 UTC, spaceo requested changes
Great! I really appreciate the effort in standardising this!
This is however implementations that conflicts with the intention of the configuration handling:
When to use Drupal snake case and the camelCasing of the react config objetcs.
The idea was to use `loadConfig()` for Drupal snake case config and `getConfig()` when integrating configuration with the apps.
Indeed the method names are not self explanatory. Could be they should be renamed? 🤔

2023-05-30 11:15 UTC, spaceo commented on config/sync/dpl_fbs.settings.yml
> +baseUrl: 'https://fbs-openplatform.dbc.dk'
Please change this into snake case. As mentioned [here](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/250#discussion_r1209895164).

2023-05-30 11:15 UTC, spaceo commented on web/modules/custom/dpl_dashboard/src/Form/DashboardSettingsForm.php
> +    $config = $this->configService->getConfig();
Please use `loadConfig()` as mentioned [here](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/250#discussion_r1209895164).

2023-05-30 11:15 UTC, spaceo commented on web/modules/custom/dpl_dashboard/src/Plugin/Block/DashboardBlock.php
> +      '#name' => 'DashBoard',
Please use snake case in theme name. That is what we have done in other [places](https://github.com/danskernesdigitalebibliotek/dpl-cms/blob/64d430729cd35f5a7315ae68abc16bec7dae9ff9/web/modules/custom/dpl_react_apps/src/Controller/DplReactAppsController.php#L149).

2023-05-30 11:15 UTC, spaceo commented on web/modules/custom/dpl_loans/src/Form/LoanListSettingsForm.php
> +    $config = $this->configService->getConfig();
Please use `loadConfig` as mentioned earlier. And change conf keys correspondingly.

2023-05-30 11:15 UTC, spaceo commented on web/modules/custom/dpl_publizon/src/Form/PublizonSettingsForm.php
> +    $config = $this->configService->getConfig();
Please use loadConfigand change keys

2023-05-30 11:15 UTC, spaceo commented on web/modules/custom/dpl_recommender/src/Form/RecommenderSettingsForm.php
> +    $config = $this->configService->getConfig();
Please use loadConfigand change keys

2023-05-30 11:15 UTC, spaceo commented on web/modules/custom/dpl_reservations/src/Form/ReservationListSettingsForm.php
> +    $config = $this->configService->getConfig();
Please use loadConfigand change keys

2023-05-30 11:15 UTC, spaceo commented on web/modules/custom/dpl_fbs/src/Form/FbsSettingsForm.php
> +    $config = $this->configService->getConfig();
Please use loadConfigand change keys

2023-05-30 11:15 UTC, spaceo requested changes
Great! I really appreciate the effort in standardising this!
This is however implementations that conflicts with the intention of the configuration handling:
When to use Drupal snake case and the camelCasing of the react config objetcs.
The idea was to use `loadConfig()` for Drupal snake case config and `getConfig()` when integrating configuration with the apps.
Indeed the method names are not self explanatory. Could be they should be renamed? 🤔

2023-05-31 11:50 UTC, cableman commented
Nice to known... might need better documentation.

2023-05-31 12:03 UTC, merged

2023-05-31 12:03 UTC, cableman commented
Reverted to using loadConfig and merged due to no more comments