Adding documentation about handling cron for PR environments
danskernesdigitalebibliotek/dpl-cms pull request #340
Opened 2023-06-06 09:28 UTC by spaceo

#### Link to issue

https://reload.atlassian.net/browse/DDFMINI-12

#### Description

Adding documentation about handling cron for PR environments

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2023-06-06 09:43 UTC, kasperg requested changes
:+1: the content looks good but there are a lot of linting errors.

Also remember to remove the current implementation of poor mans cron that was introduced in #188.

2023-06-06 09:43 UTC, kasperg commented on docs/lagoon-environments.md
> +On root level you specify the environment you want to address (eg.: `main`). And on the sub level of that you can define the cron settings.
```suggestion
On root level you specify the environment you want to address (eg.: `main`). [On the sub level of that you can define the cron settings](https://docs.lagoon.sh/using-lagoon-the-basics/lagoon-yml/#environmentsnamecronjobs).
```

Having the key info first hand is good. Adding a reference to the documentation of cron jobs for bonus points.

2023-06-07 07:33 UTC, cableman approved these changes

2023-06-07 08:04 UTC, kasperg approved these changes

2023-06-13 14:13 UTC, merged