Tweak the editor experience for event series. DDFFORM-125
danskernesdigitalebibliotek/dpl-cms pull request #631
Opened 2024-01-15 10:29 UTC by rasben

#### Link to issue

Please add a link to the issue being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2024-01-15 19:49 UTC, kasperg requested changes
:+1: Lots of code, lots of comments. Good stuff!

2024-01-16 11:48 UTC, rasben commented on config/sync/field.field.eventinstance.default.field_teaser_image.yml
👍 I didnt know i had to do it manually

2024-01-16 11:52 UTC, rasben commented on Taskfile.yml
> +      - task dev:cli -- drush user:role:add 'patron' patron
oops, that was the idea, but i forgot it : ' )

2024-01-16 11:53 UTC, rasben commented on Taskfile.yml
> +      - npx eslint web -c .eslintrc.json --fix
I'd love to add a explanation, but I have no idea why. I'm just following the precedent.

From what I can see, the other npm commands in the taskfile.yml are also run locally, and there isnt even a NPM docker container I can run it in

2024-01-16 11:54 UTC, rasben commented on web/modules/custom/dpl_admin/dpl_admin.module
> +    !method_exists($output, '__toString')) {
You'd think so, but PHPStan is very upset if i dont add this line.
I think it's a bug with PHPStan

2024-01-16 11:57 UTC, rasben commented on web/modules/custom/dpl_admin/dpl_admin.module
> +    if (method_exists($event_series, 'id')) {
I ran into the same PHPStan issue as I mentioned before.

2024-01-16 12:05 UTC, rasben commented on config/sync/field.field.eventseries.default.field_teaser_image.yml
> +description: "The teaser fields are used for the card of display.\r\nIf no image has been selected, the text will be shown instead:\r\n\r\n<img src=\"/themes/custom/novel/images/teaser-text-image.jpg
I think it's a good point, but, as you also allude to, it's outside the scope of events, so i think it's a conversation we should have with DDF during a demo

2024-01-16 12:06 UTC, rasben commented on config/sync/views.view.event_admin.yml
I'll add a 'edit series' button, but further discussion is something i think should happen during demo, as i'm kinda winging it here :)

2024-01-17 10:24 UTC, kasperg commented on web/modules/custom/dpl_admin/dpl_admin.module
> +    !method_exists($output, '__toString')) {
That was not the case. I could remove it without problems in fa35d7a1fe430f2b836696baec745c26a89974c9.

2024-01-17 10:24 UTC, kasperg commented on web/modules/custom/dpl_admin/dpl_admin.module
> +    if (method_exists($event_series, 'id')) {
This turned out to be a problem with the Recurring Events module: https://www.drupal.org/project/recurring_events/issues/3415222.

I have fixed this in 795176a542acb739a3adbafb78d3770bf48a2d3a.

2024-01-17 10:25 UTC, kasperg commented on config/sync/field.field.eventinstance.default.field_teaser_image.yml
I have done so in 8c0891eda540a6a707f10d9fb9592fd2fd0d92b7 and c8104ddfc98ad012a6d951e786f985cfd99170a5.

2024-01-17 10:27 UTC, kasperg commented on config/sync/recurring_events.eventseries.config.yml
> -enabled_fields: 'consecutive_recurring_date,daily_recurring_date,weekly_recurring_date,monthly_recurring_date,yearly_recurring_date,custom'
I have reenabled it in 892f3b2ed8f725e00e3fa50d62d6804837453efc.

2024-01-17 13:55 UTC, merged