Cleanup `field--field-categories.html.twig` and add classes to templates using this file
danskernesdigitalebibliotek/dpl-cms pull request #733
Opened 2024-02-06 12:29 UTC by kasperbirch1

#### Depend on:
https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/485

#### Description
This pull request cleanup `field--field-categories.html.twig` and add classes to templates using this file

2024-02-06 13:07 UTC, rasben requested changes

2024-02-06 13:07 UTC, rasben commented on web/themes/custom/novel/templates/fields/field--eventinstance--event-categories--full.html.twig
> +  {% set item = item|merge({'attributes': item.attributes.addClass('tag--large event-tag')}) %}
```suggestion
  {% set item = item|merge({'attributes': item.attributes.addClass('tag--large', 'event-tag')}) %}
```

2024-02-06 13:07 UTC, rasben commented on web/themes/custom/novel/templates/fields/field--eventinstance--event-categories--list-teaser.html.twig
> +  {% set item = item|merge({'attributes': item.attributes.addClass('tag--small event-list-item__tag')}) %}
```suggestion
  {% set item = item|merge({'attributes': item.attributes.addClass('tag--small', 'event-list-item__tag')}) %}
```

2024-02-07 09:10 UTC, LasseStaus approved these changes
LGTM!

2024-02-07 09:11 UTC, merged