wip
danskernesdigitalebibliotek/dpl-cms pull request #796
Opened 2024-02-22 14:38 UTC by LasseStaus

#### Link to issue

Please add a link to the issue being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2024-02-23 19:23 UTC, kasperg requested changes
:+1: Well done. I think this is well handled. 

My quips are mostly regarding suggestions for improving the generated code for the field to match our use case.

2024-02-23 19:23 UTC, kasperg commented on web/modules/custom/dpl_fbi/src/Plugin/Field/FieldType/CqlSearchItem.php
> +   * @return array<mixed>
:+1: I see that you resolved the static analysis errors whatever they were without resolving to a global ignore.

2024-02-23 19:23 UTC, kasperg commented on web/modules/custom/dpl_fbi/src/Plugin/Field/FieldType/CqlSearchItem.php
> + * Defines the 'dpl_fbi_cql_search' field type.
Consider if you can provide more information about what this field represents.

2024-02-27 13:41 UTC, LasseStaus commented on composer.json
> +            "mnsami/composer-custom-directory-installer": true
Makes sense, removed it.

2024-02-29 15:54 UTC, LasseStaus commented
Superseded by #826

2024-02-29 15:54 UTC, closed without merging