Pull event address from possible branch node. DDFFORM-402
danskernesdigitalebibliotek/dpl-cms pull request #848
Opened 2024-03-04 17:40 UTC by rasben

Making a custom field formatter, that looks up if a branch node is associated with the field, and overwrites the address with the branch address if it exists.

2024-03-05 11:21 UTC, kasperg requested changes
Please reconsider the logic in this PR-

Bascally I think you reversed the business intention. If an address is shown for the event then it should be shown. Otherwise it should fall back to the address of the related branch.

With the current approach it is not possible to have an event which is both related to a branch and with a custom address.

2024-03-05 13:17 UTC, rasben commented
@kasperg You were right - it was the other way around.

I've updated the PR now, along with adding example content.
I've also made sure that the branch is displayed on the event view.

2024-03-06 14:36 UTC, kasperg approved these changes
:+1: LGTM

A few things needs a little cleanup but I do not think the changes need another review before merging.

2024-03-06 14:36 UTC, kasperg commented on config/sync/field.field.eventinstance.default.field_branch.yml
> +description: 'When connecting a branch, it will also overwrite the event address with the address from the branch.'
Please reconsider these descriptions.

I think they are leftovers from the previous implementation where the logic was reversed.

This also applies for the three other descriptions.

2024-03-06 14:36 UTC, kasperg commented on phpstan-baseline.neon
> +
Please move this to an `ignoreErrors` entry in `phpstan.neon.dist`.

I this it is perfectly acceptable that you ignore such an error related to Drupals render arrays but ignoring it here will leave the next guy with the same hard-to-fix error when implementing a field formatter.

I think something like this should do the trick:

```
    # Field formatters return render arrays which we cannot provide more detailed typing of.
    - '#Method Drupal\\.*\\Plugin\\Field\\FieldFormatter\\.*\:\:viewElements\(\) return type has no value type specified in iterable type array\.#'
```

2024-03-06 14:36 UTC, kasperg commented on web/modules/custom/dpl_event/src/Plugin/Field/FieldFormatter/BranchAddressFormatter.php
> +    $summary[] = $this->t('Use the address from associated branch as fallback.', [], ['context' => 'DPL admin UX']);
Please reconsider the context.

If in doubt use the module name.

2024-03-06 14:36 UTC, kasperg commented on web/modules/custom/dpl_event/src/Plugin/Field/FieldFormatter/BranchAddressFormatter.php
> +class BranchAddressFormatter extends AddressDefaultFormatter {
:+1: Well done implementing this as a field formatter.

Personally I like this approach compared to an endless amount of preprocessing.

2024-03-06 14:36 UTC, kasperg commented on web/modules/custom/dpl_example_content/content/eventseries/2ce9d9b0-7f10-4a17-9a5e-383d36c1ed93.yml
> +      entity: 852d781f-82c9-40ac-bc8d-d0cefe07706d
:+1: for remembering to create/update example content with new features as we add them.

2024-03-26 08:24 UTC, merged